---
# tasks file for ansible-gentoo
- name: Deploy User's Authorized Key to Root
  authorized_key: user=root key="{{ lookup('file', pubkey) }}"

- include: storage.yml

- stat: path=/tmp/filesystem_completed
  register: filesystem_completed

- include: filesystem.yml
  when: filesystem_completed.stat.exists == False

- include: sysconf.yml
- include: kernel.yml
- include: networking.yml
- include: packages.yml
- include: system.yml
- include: reboot.yml
