- name: Install Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge {{ item.name }}' creates={{ item.creates }}
  with_items: install_packages + add_packages

- name: Remove Packages
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge -C {{ item.name }}' removes={{ item.removes }}
  with_items: rm_packages

- name: Add startup
  command: chroot /mnt/gentoo bash -c 'rc-update add {{ item }} default'
  with_items: add_startup

