
- name: Remount /dev to get /dev/mapper visible
  command: mount --rbind /dev /mnt/gentoo/dev

- name: Configure grub Defaults
  copy: src=grub_default dest=/mnt/gentoo/etc/default/grub mode=0644 owner=root group=root

- name: Install Grub to Boot Drive
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-install {{ main_disk}}'

- name: Configure Grub Make Config
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub2-mkconfig -o /boot/grub/grub.cfg'

- name: Set Root Password
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; echo "root:{{ root_passwd }}" | /usr/sbin/chpasswd'

